# Generated by Django 6.0.6 on 2026-06-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_nome_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cartaz',
            field=models.ImageField(blank=True, null=True, upload_to='cartazes/'),
        ),
    ]
